{% set name = "PyClibrary" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 4c4ab8417c314d4cd9057ad3e42e0894f3deabfde0777fe93e36bf5a83bf941e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - future
    - pyparsing >=2.3.1,<3
    - python >=3.6

test:
  imports:
    - pyclibrary
    - pyclibrary.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/MatthieuDartiailh/pyclibrary
  summary: C binding automation
  license: MIT
  license_file: LICENSE
  dev_url: https://pyclibrary.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jakirkham
    - BastianZim
