{% set name = "PyClibrary" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 735b2b42a9015a0cfdd8522b14fb9d0a66a9f790b5f0e948bda90675f54be049

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pyparsing >=2.3.1,<4
    - python >=3.6

test:
  imports:
    - pyclibrary
    - pyclibrary.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/MatthieuDartiailh/pyclibrary
  summary: C binding automation
  license: MIT
  license_file: LICENSE
  doc_url: https://pyclibrary.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jakirkham
    - BastianZim
